### ISSUE TITLE
Review of data schema

### ISSUE THREAD

**Issue by IljaCooreman** [meldet/meldet_org#5]
In the very small setup we have right now for the client-facing app Prisma is used as a CRM. A first draft for a data schema is defined on this page: 

https://github.com/meldet/meldet_org/blob/initial-setup/prisma/schema.prisma

```
enum ReportStatus {
    RECEIVED
    REVIEWED
    PUBLISHED
}

model Report {
  id                    Int        @id @default(autoincrement())
  createdAt             DateTime   @default(now())
  address               Json?
  lat                   Float
  lng                   Float
  title                 String
  description           String     @default("")
  status                ReportStatus   @default(RECEIVED)
  isPrivate             Boolean    @default(false)
  hasSocialMediaConsent Boolean    @default(false)
  categories            Category[]
}

model Category {
  id                 Int      @id @default(autoincrement())
  name               String
  description        String   @default("")
  visualisationColor String   @default("#000000")
  reports            Report[]
}
```

Can we review this?

**Comment by IljaCooreman** [comment]
in hindsight, this could've been a discussion topic as well ... still getting to know the github ecosystem 👯

**Comment by fd** [comment]
Some thoughts:
- `lat`, `lng` should be stored as strings. _floats_ may loose precision and/or change in non deterministic ways as the data moves through the system. These values should only be turned in to floats during value domain validation and while building a GIS index.
- `address` probably just needs to be a free-text value. Addresses (especially internationally) do not have a meaningful structure. As example in many countries addresses use building names/numbers instead of street names.

**Comment by codinsonn** [comment]
Aside from a `createdAt` field, we may also need an `indicentDate` field as String (so the date reference can remain fuzzy / non-frustrating to fill in), where possible, and if even necesary, we can still try to parse it in the BE via e.g. `date-fns`

**Comment by IljaCooreman** [comment]
Thx for the input, I am incorporating the changes. I was wondering if we need to store the history of the status of the ticket, so we know who moved a ticket to which status at what time. Is this useful or overkill for a first version? This also suggests we need a notion of an admin `User`, and I don't know how the greenStack backend stores its users info. Is this easy to store in a SQL database @codinsonn ?

**Comment by codinsonn** [comment]
Doesn't seem necessary for P1, I think. But once we get to having multiple admins, it may be something to reconsider?
